# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
hu:
  languageCode: Hungarian
  contentDir: content/hu
  title: Damla és Endre eskűvője
  params:
    description: Ez lesz az oldal leírása
  menu:
    main:
      - name: HU
        url: '#about'
        weight: 1

tr:
  languageCode: Turkish
  contentDir: content/tr
  title: Damla és Endre eskűvője
  params:
    description: Ez lesz az oldal leírása
  menu:
    main:
      - name: TR
        url: '#about'
        weight: 1

